services:
  runner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: github-readme-stats
    restart: unless-stopped
    environment:
      - PAT_1=${PAT_1}

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: github-readme-stats-tunnel
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    depends_on:
      - runner
    command: tunnel run

networks:
  default:
    name: github-readme-stats
